### ISSUE TITLE
How we can use it?

### ISSUE THREAD

**Issue by aaaveg** [compute-io/hmean#1]
Hello sir,
I have deckard clone finder in java.
i want to add hmean in deckard for fast processing so how can i do this ?

Deckard download from : https://github.com/skyhover/Deckard
Please help me  
Thanks
Aveg Ashish 
India

**Comment by kgryte** [comment]
This module is written in JavaScript, not Java. If you want to implement the harmonic mean, you will need to implement the algorithm yourself in Java.

**Comment by aaaveg** [comment]
sir please help me i am M.Tech student this will be my research. i dont know what to do!!

**Comment by kgryte** [comment]
Sorry, cannot be much help here. I do not see why you would want the harmonic mean anyway. I suggest looking elsewhere.

**Comment by aaaveg** [comment]
how can i implement algorithm please guide me?

**Comment by kgryte** [comment]
Read the source. See Wikipedia.

**Comment by aaaveg** [comment]
ok sir thanks much
